steps:
  - id: 'deploy-{{cookiecutter.service_name}}'
    name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'functions',
      'deploy',
      '{{cookiecutter.service_name}}',
      '--trigger-http',
      '--runtime=python39',
      '--entry-point=listen',
      '--memory=1024',
      '--set-env-vars=GCP_PROJECT=${_GCP_PROJECT}',
      '--region=europe-west1',
      '--source={{cookiecutter.service_name}}/src',
      '--service-account=${_SERVICE_ACCOUNT}'
    ]
    timeout: '600s'
